This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./hub.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file hub.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (10 comparisons).
Generating output file hub.acr....done (12 lines written, 0 warnings).
Output written in hub.acr.
Transcript written in hub.alg.
